spring.application.name=SickleCareAI

# Datasource configuration
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Root user credential
sicklecareai.root.username=${ROOT_USERNAME}
sicklecareai.root.email=${ROOT_EMAIL}
sicklecareai.root.password=${ROOT_PASSWORD}

# Mail sender configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=christianaldo515@gmail.com
spring.mail.password=tempjarbvhtirkic
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT configuration
app.secret-key=${JWT_SECRET_KEY}
app.expiration-time=900000

logging.level.org.springframework.security=DEBUG
