spring.application.name=SickleCareAI

spring.datasource.url=jdbc:postgresql://localhost:5432/sicklecareai
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
